import type { Discount } from "../types/discount";

export const seedDiscounts: Discount[] = [
  {
    code: "SAVE10",
    type: "percent",
    value: 10,
    minSubtotal: 0,
    startsAt: null,
    endsAt: null,
    usageLimit: null,
    usedCount: 0,
    isActive: true,
  },
  {
    code: "WELCOME5",
    type: "fixed",
    value: 5,
    minSubtotal: 0,
    startsAt: null,
    endsAt: null,
    usageLimit: null,
    usedCount: 0,
    isActive: true,
  },
  {
    code: "MIN50",
    type: "percent",
    value: 20,
    minSubtotal: 50,
    startsAt: null,
    endsAt: null,
    usageLimit: null,
    usedCount: 0,
    isActive: true,
  },
  {
    code: "FREESHIP",
    type: "free_shipping",
    value: 0,
    minSubtotal: 0,
    startsAt: null,
    endsAt: null,
    usageLimit: null,
    usedCount: 0,
    isActive: true,
  },
  {
    code: "EXPIRED",
    type: "percent",
    value: 50,
    minSubtotal: 0,
    startsAt: null,
    endsAt: new Date("2020-01-01T00:00:00.000Z"),
    usageLimit: null,
    usedCount: 0,
    isActive: true,
  },
];
